server:
    port: 8000

spring:

    application:
        name: sporty
    config:
        activate:
            on-profile: dev
        import: "optional:file:./.env[.properties]"

    datasource:
        driver-class-name: ${DB_DRIVER}   
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: create-drop

        show-sql: true

        properties:
            hibernate:
                "[format_sql]": true
                naming:
                physical-strategy: # conversion between camelcase and snake case
                    org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

                dialect: org.hibernate.dialect.MariaDBDialect

    data:
        redis:
            host: localhost
            port: 6379
            password:
            timeout: 6000ms

    ai:
        openai:
            api-key: ${OPEN_AI_KEY}
        chat:
            options:
                model: ${OPEN_AI_MODEL}

jwt:
    secret: ${JWT_SECRET_KEY}

openapi:
    serviceKey: ${OPENAPI_SERVICE_KEY}
    callBackUrl: ${OPENAPI_CALLBACKURL}
    dataType: ${OPENAPI_TYPE}